name: Deploy Laravel App

on:
  push:
    branches: [danu]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer update

      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-port: ${{ secrets.SSH_PORT }}

      - name: Add SSH config with custom port
        run: |
          mkdir -p ~/.ssh
          echo "Host production" >> ~/.ssh/config
          echo "  HostName ${{ secrets.SSH_HOST }}" >> ~/.ssh/config
          echo "  User danucs" >> ~/.ssh/config
          echo "  Port ${{ secrets.SSH_PORT }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Deploy Environment
        run: ./vendor/bin/envoy run deploy
